### ISSUE TITLE
Reached maximum retry limit for Request failed: 504

### ISSUE THREAD

**Issue by milanzigmond** [monti-apm/monti-apm-agent#129]
hi started to get this error recently and my stats are not being monitored on paid apps

Monti APM Error: while sending payload to Monti APM: Reached maximum retry limit for Request failed: 504

using version montiapm:agent@2.49.1

**Comment by LynchHarrison** [comment]
montiapm:agent@2.49.4
I am getting both 502 and 504.I also had a few errors on 9/06 as well but it was only a few minutes.

Screenshot shows when this started yesterday and it hasn't stopped. Dealing with around 1000+ errors within the last 24 hours.
<img width="1728" alt="Screenshot 2024-09-12 at 9 54 20 AM" src="https://github.com/user-attachments/assets/727fd652-97f6-4b9c-84dd-32690d3e62da">

**Comment by milanzigmond** [comment]
working now, I've been experiencing these only last 2 - 3 days from time to time just for the record
