### ISSUE TITLE
Using montiapm:agent@3.0.0-beta.9 may break API endpoints

### ISSUE THREAD

**Issue by bratelefant** [monti-apm/monti-apm-agent#133]
In certain scenarios, adding `montiapm:agent@3.0.0-beta.9` in a meteor 3.1 app may lead to unexpected behavior in express api endpoint. Namely, `req.query` gets `undefined`, which is normally `{}`.

I have a minimal repo [here](https://github.com/bratelefant/montiapm-agent-bug) and a forum post [here](https://forums.meteor.com/t/montiapm-agent-interfering-with-http-requests/62683) on that.

**Comment by bratelefant** [comment]
Another quick remark: In the `main` branch of my demo repo, I use a separate express installation. However, there are also issues while using meteors `WebApp.handlers`, namely when using express middleware, such as `express-openapi-validator`.

To demonstrate this as well, I added the branch [issue-using-webhandlers](https://github.com/bratelefant/montiapm-agent-bug/tree/issue-using-webhandlers). This shows the following:

If you use `WebApp.handlers` and `express-openapi-validator` as middleware without `montiapm:agent`, everything's working fine. Once you add `montiapm:agent@3.0.0-beta.9` to the `packages` file, one gets `TypeError: handler.call is not a function`.

**Comment by zodern** [comment]
Thanks for all of the information @bratelefant. I published beta 10 which should fix both issues.
