### ISSUE TITLE
Passwords in plaintext - do not save registerUser arguments

### ISSUE THREAD

**Issue by gbhrdt** [monti-apm/monti-apm-agent#15]
Hi,

`registerUser` arguments (and maybe `login` as well) should not be saved in plaintext. This is not secure.

Thanks!

**Comment by zodern** [comment]
This is coming in 2.41. You can call `Monti.tracer.redactField('fieldName')`, for example `Monti.tracer.redactField('password')` and it will remove the field's value from any object passed as a parameter to a method or publication, or if a header has that name in an incoming HTTP request, when storing the data in a trace. I tried to make it as light weight as possible - it only needs to do a shallow clone before modifying the object, and it skips cloning if the object doesn't have any redacted properties.

By default it will redact the `password` field.

**Comment by zodern** [comment]
2.41.0 has been released with this fixed.
