### ISSUE TITLE
Is this project still alive? - kadira-core:transport Error: Request failed: 502 

### ISSUE THREAD

**Issue by paulincai** [monti-apm/monti-apm-agent#18]
Hi,

I have been running on the free packages for a while and got disconnected at an unknown time in the past. I activated DEBUG via ENV vars and the servers shows: kadira-core:transport Error: Request failed: 502.
The browser shows: 

*Access to XMLHttpRequest at 'https://engine.montiapm.com/simplentp/sync' from origin 'https://act-test.herokuapp.com' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.*

I have the same situation on a second domain name running the exact same project.

How may I assist you on this?

**Comment by perbergland** [comment]
Hmm yeah all my traces (both for paid and free packages) stopped completely at noon, July 19 so I fear for the worst

**Comment by paulincai** [comment]
Thanks @perbergland. Not a resolution but a some ... enlightenment :). My main problem is all these errors in the user's browser console. It would be really good to have a status page on the Monti website for us to know if the service is fully available cause otherwise we are a little blind here.

**Comment by paulincai** [comment]
@perbergland got confirmed on my ticket on Monti APM. All ok now.
