### ISSUE TITLE
async method name

### ISSUE THREAD

**Issue by bavuongco10** [monti-apm/monti-apm-agent#30]
Monti is great but when it comes to debugging issue with async my team are clueless because lack of async method name, can we do anything about it ? After all our goal is to debug troubled async methods.
![image](https://user-images.githubusercontent.com/8337363/90074443-6f5b3c00-dd25-11ea-9694-0984d9c24680.png)

**Comment by zodern** [comment]
I replied to your post on the forums: https://forums.meteor.com/t/montiapm-async-function-name/53741

I think the [eventStackTrace](https://github.com/monti-apm/monti-apm-agent#options) option would do what you are wanting.
