### ISSUE TITLE
Agent compatible with Kadira open-source server?

### ISSUE THREAD

**Issue by edemaine** [monti-apm/monti-apm-agent#32]
I have a few open-source projects that are currently tooled to use Kadira open-source servers if the server admin wants to (via `lmachens:kadira` agent). It'd be great if I could switch to Monti's agent so that a server admin could *either* use Monti *or* use their own Kadira open-source server if they wanted. Is this agent compatible with a Kadira server? Or has the protocol deviated so that that wouldn't work?

If the answer is "yes" (compatible with Kadira open-source server), I'd suggest documenting this feature/compatibility. (I notice there's lots of backwards-compatibility already in e.g. `KADIRA_` prefix.) If the answer is "no", I imagine it'd be difficult to switch over, so feel free to close this issue.

**Comment by zodern** [comment]
I haven't tried it in a while, but it should be. I've been careful when making changes to keep all previously working features compatible, though some of the new features require changes to the engine or UI to benefit from.

**Comment by edemaine** [comment]
FWIW, I just did a bit of testing too, and it seems to be working (on my falling-over open-source server, which is why I personally want to switch to Monti -- just don't want to force others to). Great to hear your confirmation that all should work!

**Comment by zodern** [comment]
This is now documented in the readme: https://github.com/monti-apm/monti-apm-agent#compatibility
