### ISSUE TITLE
CPU problem

### ISSUE THREAD

**Issue by gbhrdt** [monti-apm/monti-apm-agent#34]
Hi,

TracerStore.processTraces takes a lot of CPU for us on a HTTP heavy app.

![Screen Shot 2020-11-26 at 00 17 46](https://user-images.githubusercontent.com/1145196/100290979-e20ec100-2f7c-11eb-9c3a-2e7f0677cdf9.png)
![Screen Shot 2020-11-26 at 00 17 36](https://user-images.githubusercontent.com/1145196/100290981-e3d88480-2f7c-11eb-8e7d-1087e05bd14d.png)

**Comment by zodern** [comment]
Thanks for reporting this @gbhrdt. This code is much faster in v2.40.1. If you are still seeing cpu issues, I have several more ideas on how to optimize it.
