### ISSUE TITLE
The http package has been deprecated, please migrate to the fetch package and new web standards.

### ISSUE THREAD

**Issue by gustawdaniel** [monti-apm/monti-apm-agent#36]
In my console:

![Screenshot from 2021-01-30 12-09-20](https://user-images.githubusercontent.com/16663028/106354674-d381b480-62f3-11eb-972f-9fc84d2c3a0d.png)

In docs:

https://docs.meteor.com/changelog.html

![Screenshot from 2021-01-30 12-10-12](https://user-images.githubusercontent.com/16663028/106354702-fb711800-62f3-11eb-96ad-53b2a2854f8b.png)

> Breaking changes
> http package has been deprecated. Please start on migrating towards the fetch package instead.

https://atmospherejs.com/meteor/fetch

**Comment by zodern** [comment]
This is fixed in 2.41.0. You can try the beta by running `meteor add montiapm:agent@2.41.0-beta.1`.
The `http` package is still a dependency since Monti APM instruments it to record outgoing http requests for traces, but I will probably make it a weak dependency in the future.
