### ISSUE TITLE
Fetched documents not showing data

### ISSUE THREAD

**Issue by ignl** [monti-apm/monti-apm-agent#40]
Hello, so I tried to connect my app to Monti from my dev env and at first everything seemed OK, there is data in Pub/Sub tab, however in Live queries basically everything is 0s. I am interested in documents fetched but it just doesn't show that any is loaded. I am using redis-oplog, maybe Monti doesn't work with it?

**Comment by zodern** [comment]
Which version of redis-oplog is your app using?
