### ISSUE TITLE
Live queries empty with redis-oplog

### ISSUE THREAD

**Issue by fumbleforce** [monti-apm/monti-apm-agent#43]
I have had this issue since I started using Monti. Nothing in the Live queries tab, which would have been extremely useful.

We are using cultofcoders:redis-oplog@2.0.5
![Screenshot_20211011_174033](https://user-images.githubusercontent.com/1506286/136818248-7b843416-6a1f-423f-a47b-9c1c0194d241.png)

**Comment by jorgeer** [comment]
PR created
