### ISSUE TITLE
Too many fetched documents (Live Queries)

### ISSUE THREAD

**Issue by chrschae** [monti-apm/monti-apm-agent#44]
Hey, 

we started using MontiAPM a few days ago and noticed we get extremely high values for fetched documents in the Live Queries section, even when the collection document count is really low, in this example we have over 1000 fetched documents for a 8 document collection, in a local development setup with only one active user. For each application, it seems like only the first subscription is affected, the fetch count for the other subscription seems normal. 

Any idea why this is happening? Anything were missing? To us it seems like a bug.

![image](https://user-images.githubusercontent.com/11799176/144031984-1defd01c-e517-4916-9896-46da9528956e.png)
![image](https://user-images.githubusercontent.com/11799176/144032138-30c46981-f33f-44ab-8ba7-f0143f83864b.png)

**Comment by zodern** [comment]
One possible cause is if the oplog isn't enabled, or the specific query can't use the oplog, Meteor will use polling. Every 10 seconds it will re-run the query to check if the results changed, which increases the number of fetched documents. To see if it is able to use the oplog, you can view a trace for the publication in the `Pub/Sub` tab. The trace will mark any queries that could not use the oplog. In development, you can view traces using [Monti APM Debug](https://github.com/monti-apm/meteor-debug).

**Comment by chrschae** [comment]
Thank you for the quick response. We are seeing that the oplog is used (screenshot attached). Is there something else that could lead to this?
![image](https://user-images.githubusercontent.com/11799176/144205728-0c8ebc56-3c11-4f1a-a4ac-0194f44bf475.png)

**Comment by chrschae** [comment]
As we were digging deeper, we saw that the oplog was indeed not used, depending on query selector. The Selector had a syntax error for some queries ( for the $in operator, not every query was passing in an array). So because of this error, the oplog was not used. A bit strange that you dont get the Error printed in the server console, thats why it was so hard to pinpoint. 
Your information really helped, thank you very much! Im now closing the issue.
