### ISSUE TITLE
Server Crash: RangeError: Invalid string length

### ISSUE THREAD

**Issue by Twisterking** [monti-apm/monti-apm-agent#51]
Hi there,

We just wanted to start using Monti in our production Meteor app! Unfortunately, after some time, it completely crashed our docker containers!

```
Error:
RangeError: Invalid string length at JSON.stringify at Kadira.sendData (monti-apm-core/dist/index.js:127:23) at packages/montiapm:agent/lib/kadria.js:204:20
```

Please fix this asap! We had to remove Monti again as it kept crashing! :(

**Comment by zodern** [comment]
This should be fixed now.
