### ISSUE TITLE
Possible to console.log all Meteor.call methods via monti?

### ISSUE THREAD

**Issue by magickaito** [monti-apm/monti-apm-agent#71]
I understand that MontiAPM is tracking of all function calls. 
We would like to see all the method calls, or even better, the response time etc, in our Heroku console.logs. Is there an option to achieve this? Like a --verbose somewhere in the configurations?

**Comment by zodern** [comment]
You could use `Monti.EventBus.on('method', callback);` to listen to the events emitted when a method ends: https://github.com/monti-apm/monti-apm-agent/blob/94e67cdec2a4dec993a69310a2add9968b991f6c/lib/hijack/wrap_session.js#L140
