### ISSUE TITLE
Manual calls of Monti.trackError doesn't include previous actions

### ISSUE THREAD

**Issue by vrizo** [monti-apm/monti-apm-agent#72]
Hello!

Thank you for this beautiful package! We use your project in Chatra, and we love it. We want to use Monti APM to debug some weird bugs. The only issue is that I don't see the preceding actions in the Monti APM Dashboard:

<img width="1221" alt="Screenshot 2022-10-25 at 15 43 38" src="https://user-images.githubusercontent.com/10763681/198691639-6639d1ce-3fa2-45d8-a32b-c26c7894ff80.png">

Compare it with the production environment when Monti catches real errors:

<img width="1250" alt="Screenshot 2022-10-25 at 15 44 01" src="https://user-images.githubusercontent.com/10763681/198691720-8b749b23-1644-4e3f-8528-a3fd8ff0b16c.png">

I added the call like this:

```javascript
Monti.trackError(new Error('Test error 2'));
```

Also, I tried to wrap it like this:

```javascript
const event = Monti.startEvent('sibInterop', {
  details: true
});

… // lots of HTTP requests

Monti.trackError(new Error('Test error 2'));

…

Monti.endEvent(event, {
  additionalDetails: true
});
```

And I set `eventStackTrace` to `true` in our `settings.json`. But nothing helps. I see only a single error message instead of a full stack trace.

Is it possible to fix it? Can you please recommend something?

Our versions:
```
meteor@1.10.0
montiapm:agent@2.45.1
montiapm:meteorx@2.2.0
```

**Comment by leonardoventurini** [comment]
Hey @vrizo where are you running that code, is it inside a method? How are you making the http calls? Which package?

The `trackError` by itself will not capture the data I am afraid. Here is my attempt, it did track database operations:

<img width="477" alt="image" src="https://user-images.githubusercontent.com/17411182/199854877-922d5ec7-0b1b-472c-bc94-3e4867205e6b.png">

<img width="1383" alt="image" src="https://user-images.githubusercontent.com/17411182/199854855-c2f73b79-bf02-4186-876d-19e5788cb115.png">

Are the options you mentioned the only ones you are using? Can you provide an anonymized version of the options for us?

**Comment by zodern** [comment]
When using `Monti.trackError`, it creates a new trace with just the start and error events: https://github.com/monti-apm/monti-apm-agent/blob/26dfdd9cb075e82814ddd52cb814bb1cfc6f8623/lib/kadira.js#L354-L362. We should have it check if there is a trace currently running, and use it.

**Comment by zodern** [comment]
@vrizo I published a beta today which fixes this. You can try it by running

```
meteor add montiapm:agent@2.47.0-beta.1 
```

**Comment by vrizo** [comment]
Thanks you, guys, @zodern @leonardoventurini! The updated version (2.47.0) works perfectly now 🎉 

<img width="1177" alt="Screenshot 2023-01-17 at 13 31 39" src="https://user-images.githubusercontent.com/10763681/212900375-87795486-d9fa-48f4-a0c7-389b5a89bc4a.png">
