### ISSUE TITLE
METEOR@1.8.1-beta.3 breaks

### ISSUE THREAD

**Issue by jorisroling** [monti-apm/monti-apm-agent#8]
```
TypeError: Cannot read property 'constructor' of undefined
    at exposeSubscription (packages/meteorhacks_meteorx.js:61:41)
    at exposeLivedata (packages/meteorhacks_meteorx.js:31:5)
    at packages/meteorhacks_meteorx.js:175:1
    at packages/meteorhacks_meteorx.js:200:4
    at packages/meteorhacks_meteorx.js:208:3

```

**Comment by s7dhansh** [comment]
https://github.com/meteorhacks/meteorx/pull/9 needs to be merged for the fix. Waiting...

**Comment by tcastelli** [comment]
Maybe it would be better to avoid keeping a link to that package and just include the needed functions inside monti directly :question:

**Comment by jorisroling** [comment]
Or, as Ben Newman puts it [here](https://github.com/meteor/meteor/issues/10337#issuecomment-441717091):

> PR #10053 converted the _namedSubs object to a Set, which seemed safe because the _ indicates it's not a stable public API. However, meteorhacks:meteorx still assumes it's an object here. Since this package hasn't been updated since 2014, I think your best options are either to remove meteorhacks:meteorx from your app, or to clone it into your local packages/ directory and change the offending code to _namedSubs.has(subId).

I'm afraid that waiting till this PR is picked up will take ages, if ever... the last commit was 3 years ago, by arunoda who left the Meteor scene. Maybe better to include it directly indeed...

**Comment by jorisroling** [comment]
See also https://github.com/meteor/meteor-apm-agent/pull/7

**Comment by zodern** [comment]
This is fixed in version 2.34.2.

**Comment by zodern** [comment]
@elie222 You can use `meteor list --tree`  to check which package is using `meteorhacks:meteorx`.

**Comment by elie222** [comment]
Thanks. It was two other packages causing the problems.

**Comment by lamhieu-vk** [comment]
use `lamhieu:meteorx` instead of `meteorhacks:meteorx` to fix it!
